version: '3.8'

services:
    db:
        image: postgres:latest
        restart: always
        env_file:
            - env/database.env
        volumes:
            - postgres-volume:/var/lib/postgresql/data

    scraper:
        restart: always
        build:
            context: ./
            dockerfile: log_scraper/Dockerfile
        env_file:
            - env/database.env
            - env/account.env
        depends_on:
            - db

    permissions:
        restart: always
        build:
            context: ./
            dockerfile: review_permissions/Dockerfile
        env_file:
            - env/database.env
            - env/account.env
        depends_on:
            - db

    bot:
        restart: always
        build:
            context: ./
            dockerfile: bot/Dockerfile
        env_file:
            - env/database.env
            - env/bot.env
        depends_on:
            - db
        volumes:
            - telethon-sessions:/bot/sessions

    tester:  # for test through `exec -it`
        restart: always
        build: .
        env_file:
            - env/database.env
            - env/account.env
        tty: true
        volumes:
            - ./:/lp3

volumes:
    postgres-volume:
    telethon-sessions:
